### ISSUE TITLE
notify_on not working

### ISSUE THREAD

**Issue by LennardWesterveld** [wantedly/step-pretty-slack-notify#21]
Hi there,

My build is successful and still getting slack notification.
So the notify_on is not working, i think the environment name is wrong.

```
    after-steps:
        - wantedly/pretty-slack-notify@0.2.11:
            webhook_url: *******
            notify_on: "failed"
            channel: ******
            username: *****
```

Result from wercker.
```
export WERCKER_PRETTY_SLACK_NOTIFY_BRANCHES=""
export WERCKER_PRETTY_SLACK_NOTIFY_NOTIFY_ON="failed"
```
